spring:
  application:
    name: cart-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/carts_service?serverTimezone=UTC
    username: root
    password: 
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  apiproduct:
    url: http://localhost:8083/products
