spring:
  application:
    name: sale-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/sales_service?serverTimezone=UTC
    username: root
    password: 
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  apicart:
    url: http://localhost:8086/carts
